name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: wei/curl@master
        with:
          args: ${{ secrets.DEPLOY_URL }}
